# Generated by Django 4.2.5 on 2023-12-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
