# Generated by Django 4.2.4 on 2024-01-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0004_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('fairy tale', '童話'), ('comic', '漫畫')], max_length=200),
        ),
    ]
