# Generated by Django 4.2.4 on 2024-01-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0005_alter_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
