# Generated by Django 4.2.5 on 2024-01-04 02:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mytext', '0007_post_condition_borrow_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrow_books',
            new_name='Borrow_book',
        ),
    ]
