# Generated by Django 4.2.5 on 2024-01-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0009_borrow_book_reader_alter_borrow_book_readerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('loan', '外借中'), ('collection', '館藏中'), ('reserve', '預約中')], max_length=20),
        ),
    ]
