# Generated by Django 4.2.5 on 2024-01-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0011_remove_borrow_book_reader_alter_borrow_book_readerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='condition',
        ),
    ]
