# Generated by Django 4.2.5 on 2024-01-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0012_remove_post_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
