# Generated by Django 4.2.5 on 2024-01-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0013_post_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow_book',
            name='return_date',
        ),
        migrations.AddField(
            model_name='borrow_book',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
