# Generated by Django 4.2.5 on 2024-01-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0014_remove_borrow_book_return_date_borrow_book_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
