# Generated by Django 4.2.5 on 2024-01-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0017_alter_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('童話', '童話'), ('漫畫', '漫畫')], max_length=200),
        ),
    ]
