# Generated by Django 5.0.1 on 2024-01-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0018_alter_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='returned',
            field=models.CharField(choices=[('已歸還', '童話'), ('尚未歸還', '漫畫')], max_length=10),
        ),
    ]
