# Generated by Django 5.0.1 on 2024-01-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0020_alter_borrow_book_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
