# Generated by Django 4.2.4 on 2024-01-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0022_borrow_book_actual_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='condition',
        ),
    ]
