# Generated by Django 4.2.4 on 2024-01-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0023_remove_post_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
