# Generated by Django 4.2.4 on 2024-01-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytext', '0024_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(max_length=200),
        ),
    ]
